### ISSUE TITLE
Milestone 4 Team Internal Review

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/CardioPredict#37]
Afterward the submission of Milestone 3, this issue thread serves as a checklist of team internal review for improving the clarity, fixing bugs and typos, enhancing writing quality, and streamlining workflow.

**Bugs and typos:**

1. [X] Citation (Tsao 2015) )missing tags in the data section

* [ ] 

**Writing quality:**

* [X] Rewrite the abstract to make it more appealing to the audience
* [ ] 

**Clarity and explaining:**

* [ ] We need a research paper title, so far we use a project title as a paper title

**Workflow and version control:**

* [ ] Clean up branches

**Comment by sandygross** [comment]
Thank you Doris for opening the Issue. I will clean up the branches and change the title.

**Comment by MDSFusionist** [comment]
I think we have completed all the tasks listed here. Thanks so much, Team!
